[WIP] Game page rendering
marmelab/quarto-isomorphic pull request #2
Opened 2018-07-09 16:40 UTC by JulienMattiussi

https://trello.com/c/xV6wZFTP

Follw #1 

- [ ] Get datas from API
- [ ] Render grid
- [ ] Render remaining pieces
- [ ] Tests rendering
- [ ] Refresh game every x time

2018-07-10 16:42 UTC, ThieryMichel requested changes

2018-07-10 16:42 UTC, ThieryMichel commented on pages/_document.js
> +        const initialProps = await Document.getInitialProps(ctx);
return directly, no need to spread since you do not add props

2018-07-10 16:42 UTC, ThieryMichel commented on pages/Game.js
> +        let url = `http://${config.apiUrl}/479`;
create a dataProvider with a getGame method, and use it to fetch all the needed resource. Make it isomorphic with isomorphic fetch, so you can use it here and server side in the socket logic.

2018-07-10 16:42 UTC, ThieryMichel commented on server.js
> +        request(url, function(error, response, body) {
Use the dataProvider.getGame

2018-07-10 16:42 UTC, ThieryMichel commented on src/game/ActionText.js
> +    } else if (props.watch_only) {
just if the else is unneeded.

2018-07-10 16:42 UTC, ThieryMichel commented on src/ui/Button.js
> +    -o-text-overflow: clip;
remove opera specific css

2018-07-10 16:50 UTC, Luwangel requested changes

2018-07-10 16:50 UTC, Luwangel commented on config/config.dist.js
> +    //apiUrl: 'http://192.168.86.248/gameapi',
Remove this line from the dist

2018-07-10 16:50 UTC, Luwangel commented on pages/Game.js
> +        let url = `http://${config.apiUrl}/479`;
The url could be a constant defined at the root of the file (to avoid useless computation).

2018-07-10 16:50 UTC, Luwangel commented on pages/Game.js
>  class Game extends React.Component {
Use directly `Component`: `import React, { Component } from 'react';`

2018-07-10 16:50 UTC, Luwangel commented on pages/Game.js
> +            loaded: data.grid ? true : false,
You can cast to a boolean value: `!!data.grid`

2018-07-11 08:25 UTC, Kmaschta commented on src/game/GridBox.js
> +        label={'gridbox_x' + String(props.x) + '_y' + String(props.y)}
Take advantage of template strings: `gridbox_x${props.x}_y${props.y}`

2018-07-11 08:25 UTC, Kmaschta commented on src/game/RemainingBox.js
> +        label={'remainingbox'}
When the prop is only a string you can avoid the brakets: `label="remainingbox"`

2018-07-12 07:27 UTC, ThieryMichel approved these changes

2018-07-12 07:28 UTC, merged