[WIP] Playing game
marmelab/quarto-isomorphic pull request #5
Opened 2018-07-12 14:07 UTC by JulienMattiussi

- [ ] User can create a game
- [ ] User can play at his turn
- [ ] Board refresh at opponent turn

2018-07-16 08:23 UTC, ThieryMichel requested changes

2018-07-16 08:23 UTC, ThieryMichel commented on server.js
> +        console.log(`game ${req.params.idGame} refreshed`);// eslint-disable-line
Tip: You can use window.console.log, and eslint will say nothing

2018-07-16 08:23 UTC, ThieryMichel commented on pages/Game.js
> +        let gameData = {};
const { query } = props;

2018-07-16 08:23 UTC, ThieryMichel commented on pages/Game.js
> +            gameData = await getGame(
const { idGame, ...} = query;

2018-07-16 08:23 UTC, ThieryMichel commented on pages/Game.js
> +            idGame: gameData.idGame,
const { idGame, game, ... } = gameData;
return {
    idGame,
    game,
    ...
};

2018-07-16 08:23 UTC, ThieryMichel commented on pages/Game.js
> +
const { idGame, ...} = this.props;

2018-07-16 08:23 UTC, ThieryMichel commented on src/game/Box.js
>      props => ({
({ boxSize, winningBox, clickable, ... }) =>

2018-07-16 08:23 UTC, ThieryMichel commented on src/game/GridBox.js
> +const GridBox = props => {
destructure props, to avoid repeating props.***

2018-07-16 08:23 UTC, ThieryMichel commented on src/game/RemainingBox.js
> +const RemainingBox = props => {
destructure props

2018-07-16 08:23 UTC, ThieryMichel commented on src/game/WinningText.js
> +const getWinningText = props => {
declare getWinningText before you use it

2018-07-16 08:23 UTC, ThieryMichel commented on src/game/WinningText.js
> +const getWinningText = props => {
pass directly closed, youWon and winnerId as argument

2018-07-16 08:23 UTC, ThieryMichel commented on src/game/WinningText.js
> +const WinningText = props => (
destructure props

2018-07-16 08:23 UTC, ThieryMichel commented on src/game/WinningText.js
> +    props => ({
destructure props

2018-07-16 08:23 UTC, ThieryMichel commented on src/list/GameList.js
> +    props => ({
destructure color from props

2018-07-16 08:23 UTC, ThieryMichel commented on src/list/GameList.js
> +    props => ({
destructure

2018-07-16 08:23 UTC, ThieryMichel commented on src/list/GameList.js
>      static getDerivedStateFromProps = props => {
destructure

2018-07-16 08:23 UTC, ThieryMichel commented on src/services/gameService.js
> +    return fetch(url)
add a fetchService that incorporate the json parsing and the error handling

2018-07-16 08:23 UTC, ThieryMichel commented on src/services/gameService.js
> +                idGame: res.idGame,
{ ...res, token: res.tokenPlayerOne }

2018-07-16 08:23 UTC, ThieryMichel commented on src/services/storageService.js
> +const tokenStorage = `${prefixStorage}gameTokens`;
it would be even better to inject the wanted storage as a dependency.

2018-07-16 08:23 UTC, ThieryMichel commented on src/services/warningService.js
> +export const logFetchError = error => {
logFetchError, logStorageError and logCustomError are identical, keep only one.

2018-07-16 08:23 UTC, ThieryMichel commented on src/ui/LoadingZone.js
> +const LoadingZone = props => {
destructure

2018-07-16 12:17 UTC, JulienMattiussi commented on src/services/warningService.js
> +export const logFetchError = error => {
Actually, they are not equal, a default message error depends of wich fonction you called, I did that to avoid repeating same message to each call

2018-07-17 12:22 UTC, JulienMattiussi commented on src/services/gameService.js
> +                idGame: res.idGame,
Personnaly, I prefer to keep game object structure as it was given by API all along pages.

2018-07-18 15:21 UTC, Luwangel requested changes

2018-07-18 15:21 UTC, Luwangel commented on pages/Game.js
> +        const { query } = props;
You could simplify this method writing something lilke:
 
``` js
    const { query } = props;

    let { game, token } =
        query && query.idGame
            ? await getGame(query.idGame, query.token, query.register)
            : await newGame(2);

    return {
        idGame: game.idGame,
        game: game,
        token: token || query.token,
        loaded: !!game.grid,
    };
```

2018-07-18 15:21 UTC, Luwangel commented on src/services/gameService.js
> +    return fetch(url)
You can return directly
```js
async url => await fetch(url).then(...).catch(...);
```

2018-07-18 15:21 UTC, Luwangel commented on src/services/gameService.js
> +    if (register) {
```js
let url = `${config.apiUrl}/${idGame}${
    register ? '?register=1' : '?token=' + token
}`;
```

2018-07-18 15:21 UTC, Luwangel commented on src/services/listenerService.js
>      if (gameListenersList[idGame]) {
``` js
if (!gameListenersList[idGame]) {
    return;
}
// ....
```

2018-07-18 15:21 UTC, Luwangel commented on src/services/warningService.js
> +    console.log(error); // eslint-disable-line
You can use `console.error`. And I think it's not useful to have two logs.

2018-07-19 07:26 UTC, Luwangel requested changes

2018-07-19 07:26 UTC, Luwangel commented on src/services/storageService.test.js
> +/* jest.mock('./storageService');
You can remove this line

2018-07-19 07:26 UTC, Luwangel commented on src/services/storageService.test.js
> +        getItem: element => JSON.stringify(dataStored), // eslint-disable-line no-unused-vars
You don't need to pass the element in the parameters if you don't use it.

`() => JSON.stringify(dataStored)`

2018-07-19 07:26 UTC, Luwangel commented on src/services/storageService.test.js
> +    const testStorage = {
You can test that the storage method has been called using spies or something like that.

https://jestjs.io/docs/en/jest-object#jestspyonobject-methodname

2018-07-19 08:26 UTC, Luwangel approved these changes

2018-07-19 08:26 UTC, merged